# Testverbesserung

-- fehlerhafter Code
-- Probleme
-- korrigierter Code

#### ResultsRestClient.java
###### Definieren des aktuellen Rennfahrers:
  * Alter Code

[source,java]
----
    Driver currentDriver = query.getSingleResult();
    System.out.println(currentDriver);
----

  * Probleme mit dem alten Code:
    ** Mit diesem Code bekomme ich immer einen "no entity found for query" - Error

  * Lösung des Problems => korrigierter Code
    ** Das if-Statement wird dazu gebraucht, um zu überprüfen,
       ob der aktuelle Fahrer auch in der Datenbank gespeichert ist.
       Ist er ein, oder auch mehrmals in der Datenbank gespeichert,
       so wird der erste Eintrag in der Liste verwendet

[source,java]
----
    List<Driver> drivers = query.getResultList();
    if (drivers.size() >= 1){
        Driver currentDriver = drivers.get(0);
        System.out.println(currentDriver);
        ...
    }
----

###### Definition des aktuellen Rennens:
  * Alter Code:
[source,java]
----
    //String raceId = object.get("raceNo").toString();
    //int raceNumber = Integer.parseInt(raceId);
    //Race currentRace = this.em.createNamedQuery("Race.findById", Race.class).setParameter("ID", raceNumber).getSingleResult();
----

  * Probleme mit dem alten Code:
    ** Der Code konnte nicht funktionieren, da er auskommentiert war.
    ** Der definierte String ist kein "richtiger" String und funktioniert beim Übergeben nicht.
    ** Der String wird zwar mit Integer.parseInt(raceId) in einen int umgewandelt,
       jedoch ist die ID des Rennens ein long und kein int und so kann die query nicht funktionieren.

  * Neuer Code:
    ** Es gibt die Funktion .getInt und so kann ich gleich einen int vom JsonObject lesen
       und diesen dann als long kasten.
[source,java]
----
    int raceId = object.getInt("raceNo");
    long raceNumber = (long) raceId;
    Race currentRace = this.em
        .createNamedQuery("Race.findById", Race.class)
        .setParameter("ID", raceNumber)
        .getSingleResult();
----


