# Testverbesserung

-- fehlerhafter Code
-- Probleme
-- korrigierter Code

### Aufgabe 1: Import CSV

### Aufgabe 2: Import Rest

#### ResultsRestClient.java
###### Definieren des aktuellen Rennfahrers:
  * Alter Code

[source,java]
----
    Driver currentDriver = query.getSingleResult();
    System.out.println(currentDriver);
----

  * Probleme mit dem alten Code:
    ** Mit diesem Code bekomme ich immer einen "no entity found for query" - Error

  * Lösung des Problems => korrigierter Code
    ** Das if-Statement wird dazu gebraucht, um zu überprüfen,
       ob der aktuelle Fahrer auch in der Datenbank gespeichert ist.
       Ist er ein, oder auch mehrmals in der Datenbank gespeichert,
       so wird der erste Eintrag in der Liste verwendet

[source,java]
----
    List<Driver> drivers = query.getResultList();
    if (drivers.size() >= 1){
        Driver currentDriver = drivers.get(0);
        System.out.println(currentDriver);
        ...
    }
----

###### Definition des aktuellen Rennens:
  * Alter Code:
[source,java]
----
    //String raceId = object.get("raceNo").toString();
    //int raceNumber = Integer.parseInt(raceId);
    //Race currentRace = this.em.createNamedQuery("Race.findById", Race.class).setParameter("ID", raceNumber).getSingleResult();
----

  * Probleme mit dem alten Code:
    ** Der Code konnte nicht funktionieren, da er auskommentiert war.
    ** Der definierte String ist kein "richtiger" String und funktioniert beim Übergeben nicht.
    ** Der String wird zwar mit Integer.parseInt(raceId) in einen int umgewandelt,
       jedoch ist die ID des Rennens ein long und kein int und so kann die query nicht funktionieren.

  * Neuer Code:
    ** Es gibt die Funktion .getInt und so kann ich gleich einen int vom JsonObject lesen
       und diesen dann als long kasten.
[source,java]
----
    int raceId = object.getInt("raceNo");
    long raceNumber = (long) raceId;
    Race currentRace = this.em
        .createNamedQuery("Race.findById", Race.class)
        .setParameter("ID", raceNumber)
        .getSingleResult();
----

###### Definition der aktuellen Position, erstellen des Results und in DB speichern

  * Alter Code
[source,java]
----
//            String currentPosition = object.get("driverFullName").toString();
//            int currentPos = Integer.parseInt(currentPosition);
//
//              Result currentResult = new Result();
//              currentResult.setRace(currentRace);
//              currentResult.setPosition(currentPos);
//              currentResult.setDriver(currentDriver);
//              currentResult.setPoints(currentPos);
//
//            this.em.persist(currentResult);
//            System.out.println(object);
----

* Probleme mit dem alten Code
    ** Da der Code auskommentiert war, konnte er nicht funktionieren.
    ** Der String namens currentPosition gibt den aktuellen Fahrer aus und
       kann daher auch nicht in einen int geparst werden.
    ** Die aktuelle Position kann nicht als Position des aktuellen Results gesetzt werden,
       da ein int erwartet wird und auch schon ein Fehler beim Parsen geworfen wird.
    ** Auch die Punkte können nicht im aktuellen Result gesetzt werden,
       da eben currentPos nicht verwendet werden kann. Außerdem sind es auch nicht die Punkte für den aktuellen Platz.

* Neuer Code
[source,java]
----
    int currentPosition = object.getInt("position");
    Result currentResult = new Result();
    currentResult.setRace(currentRace);
    currentResult.setPosition(currentPosition);
    currentResult.setDriver(currentDriver);
    int currentPoints = currentResult.pointsPerPosition[currentPosition];
    currentResult.setPoints(currentPoints);
    this.em.persist(currentResult);
    System.out.println(object);
----

### Aufgabe 3: Gesamtpunkte eines Fahrers

* Result:
  ** Erstellung einer NamedQuery, zum Auslesen der Gesamtpunkte eines bestimmten Fahrers.
[source,java]
----
    @NamedQueries({
            @NamedQuery(
                    name = "Result.getPointSumofDriver",
                    query = "select sum(r.points) from Result r where r.driver = :DRIVER"
            )
    })
----

### Aufgabe 4: Sieger eines bestimmten Rennens
### Aufgabe 5: Liste der Rennen, die ein Team gewonnen hat
### Aufgabe 6(für Spezialisten): Liste aller Fahrer mit ihren Punkten

